name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  freebsd:
    name: freebsd-vm@${{ matrix.vmactions }} ${{ matrix.osrelease }} (${{ matrix.iteration }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        iteration: [1, 2, 3, 4, 5]
        vmactions: [v1.2.0, v1.2.1]
        osrelease: ["13.3", "14.2", "15.0"]

    steps:
      - name: Boot VM
        if: ${{ matrix.vmactions == 'v1.2.0' }}
        uses: vmactions/freebsd-vm@v1.2.0
        with:
          arch: aarch64
          release: ${{ matrix.osrelease }}
          prepare: |
            pkg install -y wget gmake

      - name: Boot VM
        if: ${{ matrix.vmactions == 'v1.2.1' }}
        uses: vmactions/freebsd-vm@v1.2.1
        with:
          arch: aarch64
          prepare: |
            pkg install -y wget gmake

      - name: Build
        shell: freebsd {0}
        run: |
          wget https://github.com/bjia56/build-dependencies/releases/download/portable-python/ncurses-6.4.tar.gz
          tar -xf ncurses-6.4.tar.gz
          cd ncurses-6.4
          ./configure
          gmake -j$(nproc)